// A port of Unima's KnowledgeResolver. PHP is normative; this file is proven, not trusted.
//
// WHY A SECOND IMPLEMENTATION EXISTS AT ALL. This repo has to answer "which rules apply here"
// offline, and the answer cannot be precomputed. Filtering must precede shadowing — a rule may only
// be beaten by a rule that actually applies in this context — so a per-scope slice cannot be
// computed first and filtered by slot afterwards. Getting that order wrong is invisible and did real
// damage once: shadowing first meant generating a German email subject dropped the Sie-form rule
// entirely, because a channel-scoped exception shadowed it and was then itself filtered out for being
// email-only. No rule about form of address reached the model, and nothing reported a problem.
// Precomputing every (language x market x product x segment x slot x channel x discipline) is ~19,000
// combinations for one corpus. So: a port.
//
// WHAT MAKES IT LEGITIMATE RATHER THAN A PARALLEL WORLD. knowledge/_conformance/cases.json is
// generated by the PHP resolver itself and enumerates the contexts the corpus actually contains, with
// the resolved key order, the drop reasons, the line count and the exact prompt bytes. `npm test` /
// `node scripts/conformance.mjs` runs this file against every case. A divergence is a bug in THIS
// file until proven otherwise. One truth, one authority, one gate.
//
// If you change this file, run the conformance script before committing. If a case fails and you
// believe PHP is wrong, fix PHP — do not "fix" the case.

import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

/** Budget ranking weights. Mirrors Modality::weight(). Never reorder. */
const MODALITY_WEIGHT = { must: 300, should: 200, may: 100 }

/**
 * Families that must stay one rule per line. Tone and copy principles read as distinct directives
 * and lose force when bundled under a heading; formatting families do not. Mirrors
 * RuleCompactor::NEVER_GROUP.
 */
const NEVER_GROUP = new Set(['tone_pillar', 'copy_principle', 'product_tone', 'form_of_address'])

/**
 * Families a given PURPOSE refuses. Mirrors RulePurpose::excludedFamilies() — same names, same
 * order, and the same direction of travel.
 *
 * A DENY LIST, NOT AN ALLOW LIST, and the direction is the safety argument: an unknown family is
 * ADMITTED, so the worst case of getting this list wrong is a longer prompt, never an obligation
 * that quietly disappeared. Read the PHP enum for why each family is here.
 */
const PURPOSE_EXCLUDED_FAMILIES = {
  any: [],
  strategy: [
    'abbreviation',
    'anglicism',
    'capitalization',
    'grammar',
    'hyphenation',
    'punctuation',
    'spelling',
    'typography',
    'address_format',
    'currency',
    'measurement',
    'numbers',
    'phone_format',
    'accessibility',
    'cta',
    'sender',
    'seo',
    'ux_writing',
  ],
}

/** Scope coordinates, in specificity-weight order. Mirrors ScopeDimension. */
const SCOPE_DIMENSIONS = ['product', 'market', 'audience_segment', 'language']
const SPECIFICITY_WEIGHT = { product: 8, market: 4, audience_segment: 2, language: 1 }

/** Closed predicate vocabulary. Mirrors ConditionEvaluator::ALLOWED_KEYS. */
export const ALLOWED_CONDITION_KEYS = [
  'platform',
  'communication_type',
  'audience_tier',
  'persona_role',
  'market_availability',
  'market_context',
  'addressed_informally',
]

export const DROP_REASONS = {
  OutOfScope: 'out_of_scope',
  WrongSlot: 'wrong_slot',
  WrongChannel: 'wrong_channel',
  WrongDiscipline: 'wrong_discipline',
  WrongPurpose: 'wrong_purpose',
  NotMachineActionable: 'not_machine_actionable',
  OutsideEffectiveWindow: 'outside_effective_window',
  ConditionNotMet: 'condition_not_met',
  ShadowedByMoreSpecific: 'shadowed_by_more_specific',
  Suppressed: 'suppressed',
  Superseded: 'superseded',
  OverBudget: 'over_budget',
}

// ── loading ────────────────────────────────────────────────────────────────────────────────────────

/**
 * Flattens knowledge/rules/index.yaml into the row shape the walk needs.
 *
 * The index is keyed by rule key and each key holds a LIST, because the cascade allows one key at
 * several scopes. Flattening to one row per key is the single most tempting mistake here and it
 * silently drops every market override.
 */
export function flattenIndex(index) {
  const rows = []

  for (const [key, variants] of Object.entries(index.rules ?? {})) {
    for (const v of variants) {
      rows.push({
        key,
        family: v.family,
        discipline: v.discipline,
        effect: v.effect,
        modality: v.modality,
        modality_inferred: v.modality_inferred === true,
        enforcement: v.enforcement,
        machine_actionable: v.machine_actionable === true,
        // Recomputed from the scope rather than read from the file. The stored value is a
        // PostgreSQL STORED GENERATED column, and if the two ever disagree the arithmetic is the
        // thing to trust — an in-memory row reads 0.
        specificity: specificityOf(v.scope),
        stored_specificity: v.specificity ?? null,
        priority: v.priority ?? null,
        instruction: v.instruction ?? '',
        caveat: v.caveat ?? null,
        exhaustive: v.exhaustive ?? null,
        overrides_cldr: v.overrides_cldr ?? null,
        slots: v.slots ?? [],
        channels: v.channels ?? [],
        applies_when: v.applies_when ?? {},
        scope: {
          product: v.scope?.product ?? null,
          market: v.scope?.market ?? null,
          audience_segment: v.scope?.audience_segment ?? null,
          language: v.scope?.language ?? null,
        },
        broadcast_asserted: v.broadcast_asserted ?? [],
        effective_from: v.effective_from ?? null,
        effective_to: v.effective_to ?? null,
        source_locator: v.source_locator ?? null,
        // The key this row explicitly retires. Step 3.5 of the walk READS this — and it was missing
        // from this mapping while `resolve()` referenced `rule.supersedes`, so `undefined ?? null`
        // meant supersession silently never fired on the JS side. No rule in the corpus supersedes
        // another today, which is precisely why the conformance suite could not catch it: PHP and JS
        // agreed on every case by both doing nothing.
        //
        // `supersedes` REMOVES its target, which is a different mechanism from an `exception_to`
        // relation — that one keeps both rules and states the relationship. Conflating them would
        // silently delete a rule the source still considers in force.
        supersedes: v.supersedes ?? null,
        relations: v.relations ?? [],
      })
    }
  }

  return rows
}

export function specificityOf(scope) {
  let total = 0
  for (const dimension of SCOPE_DIMENSIONS) {
    if ((scope?.[dimension] ?? null) !== null) {
      total += SPECIFICITY_WEIGHT[dimension]
    }
  }
  return total
}

// ── the walk ───────────────────────────────────────────────────────────────────────────────────────

/**
 * Resolve for one context. Returns { rules, checks, lines, dropped, ... } mirroring ResolvedRuleSet.
 *
 * context: { language, market, product, audience_segment, slot, channel, discipline, purpose,
 *            budget, machine_actionable_only, conditions, as_of }
 *
 * All scope values are BUSINESS KEYS (language code, market code, product name, segment key), never
 * uuids — the ids are v4 and change on every fixture reload.
 */
export function resolve(rows, context = {}) {
  const ctx = {
    language: context.language ?? null,
    market: context.market ?? null,
    product: context.product ?? null,
    audience_segment: context.audience_segment ?? null,
    slot: context.slot ?? null,
    channel: context.channel ?? null,
    discipline: context.discipline ?? 'writing',
    // Defaults to 'any' — no opinion, every family in scope — so a caller that says nothing gets
    // exactly the set it got before this axis existed. An UNKNOWN purpose also refuses nothing
    // (see purposeAdmits), for the same reason the list is a deny list: a typo must not silently
    // empty a prompt.
    purpose: context.purpose ?? 'any',
    budget: context.budget ?? 12,
    machine_actionable_only: context.machine_actionable_only ?? true,
    conditions: context.conditions ?? {},
    as_of: context.as_of ?? null,
  }

  const dropped = []
  const candidateCount = rows.length

  // --- steps 1 and 2: scope, then every filter ---------------------------------------------------
  const applicable = []
  for (const rule of rows) {
    const reason = rejectionReason(rule, ctx)
    if (reason !== null) {
      dropped.push(drop(rule, reason))
      continue
    }
    applicable.push(rule)
  }

  // --- step 3: shadow by key, highest specificity wins -------------------------------------------
  const winners = new Map()
  for (const rule of applicable) {
    const incumbent = winners.get(rule.key)

    if (incumbent === undefined) {
      winners.set(rule.key, rule)
      continue
    }

    if (rule.specificity > incumbent.specificity) {
      winners.set(rule.key, rule)
      dropped.push(drop(incumbent, DROP_REASONS.ShadowedByMoreSpecific, rule.key))
    } else {
      dropped.push(drop(rule, DROP_REASONS.ShadowedByMoreSpecific, incumbent.key))
    }
  }

  // --- explicit supersession removes its target --------------------------------------------------
  // Iterating a snapshot: PHP iterates `$winners` while unsetting from it, which is safe there and
  // is not safe on a live Map here.
  for (const [key, rule] of [...winners]) {
    const target = rule.supersedes ?? null
    if (target !== null && winners.has(target)) {
      dropped.push(drop(winners.get(target), DROP_REASONS.Superseded, key))
      winners.delete(target)
    }
  }

  // --- step 4: suppression removes the key and offers no replacement -----------------------------
  for (const [key, rule] of [...winners]) {
    if (rule.effect === 'suppress') {
      dropped.push(drop(rule, DROP_REASONS.Suppressed, key))
      winners.delete(key)
    }
  }

  // --- step 5: split tracks ----------------------------------------------------------------------
  // A rule verified against the OUTPUT does not compete for prompt budget. On the loaded IONOS data
  // that moves 32 of 69 rules — number formatting, punctuation, hyphenation, orthography — off a
  // track where they were followed probabilistically onto one where they are checked exactly.
  const promptable = []
  const checkable = []
  for (const rule of winners.values()) {
    if (rule.enforcement === 'instruct' || rule.enforcement === 'both') promptable.push(rule)
    if (rule.enforcement === 'check' || rule.enforcement === 'both') checkable.push(rule)
  }

  // --- step 6: rank, compact, truncate ONLY the optional tail -------------------------------------
  const ranked = rank(promptable, ctx.slot, ctx.channel)
  const resolveRule = (rule) => ({ ...rule, exceptions: exceptionsFor(rule, winners) })

  const allLines = toLines(ranked.map(resolveRule))
  const mandatoryLines = allLines.filter((l) => l.modality === 'must')
  const optionalLines = allLines.filter((l) => l.modality !== 'must')

  // An obligation is not negotiable. Every mandatory line is emitted even when they alone exceed the
  // budget; the budget then REPORTS that the data needs retuning rather than quietly picking which
  // brand rules to disobey.
  const mandatoryExceedsBudget = mandatoryLines.length > Math.max(0, ctx.budget)
  const room = Math.max(0, ctx.budget - mandatoryLines.length)
  const keptOptional = optionalLines.slice(0, room)

  for (const overflow of optionalLines.slice(keptOptional.length)) {
    for (const rule of overflow.rules) {
      dropped.push({
        key: rule.key,
        specificity: rule.specificity,
        reason: DROP_REASONS.OverBudget,
        modality: rule.modality,
        beaten_by: null,
        source_locator: rule.source_locator ?? null,
      })
    }
  }

  const lines = [...mandatoryLines, ...keptOptional]
  const rules = lines.flatMap((l) => l.rules)

  return {
    rules,
    checks: rank(checkable, ctx.slot, ctx.channel).map(resolveRule),
    lines,
    dropped,
    budget: ctx.budget,
    candidate_count: candidateCount,
    line_count: lines.length,
    mandatory_exceeds_budget: mandatoryExceedsBudget,
    prompt: renderPrompt(lines),
  }
}

/** Null when the rule applies; otherwise the FIRST reason it does not. Order mirrors PHP exactly. */
function rejectionReason(rule, ctx) {
  if (!scopeMatches(rule.scope, ctx)) return DROP_REASONS.OutOfScope
  if (rule.discipline !== ctx.discipline) return DROP_REASONS.WrongDiscipline

  // Immediately after discipline, mirroring KnowledgeResolver::rejectionReason(). Both ask "is this
  // rule about the job I am doing?", and answering purpose before slot keeps the FIRST recorded drop
  // reason meaningful: a CTA rule refused by a strategy request reads `wrong_purpose`, not
  // `wrong_slot`.
  if (!purposeAdmits(ctx.purpose, rule.family)) return DROP_REASONS.WrongPurpose

  if (ctx.machine_actionable_only && !rule.machine_actionable) return DROP_REASONS.NotMachineActionable
  if (!isEffectiveAt(rule, ctx.as_of)) return DROP_REASONS.OutsideEffectiveWindow

  // An empty filter list means "not restricted", so it matches. The tri-state distinction between
  // "explicitly every slot" and "nobody decided" lives in broadcast_asserted and is a REPORTING
  // concern — matching them differently would change which rules reach a prompt based on how
  // carefully someone filled in a form.
  if (ctx.slot !== null && rule.slots.length > 0 && !rule.slots.includes(ctx.slot)) {
    return DROP_REASONS.WrongSlot
  }
  if (ctx.channel !== null && rule.channels.length > 0 && !rule.channels.includes(ctx.channel)) {
    return DROP_REASONS.WrongChannel
  }
  if (!conditionsMatch(rule.applies_when, ctx.conditions)) return DROP_REASONS.ConditionNotMet

  return null
}

/**
 * Whether a rule of this family may reach a prompt built for this purpose. Mirrors
 * RulePurpose::admits().
 *
 * A purpose nobody has a list for refuses NOTHING. PHP cannot reach that branch — its `purpose` is a
 * backed enum, so an unknown value fails at construction — but JS receives a bare string off a
 * webhook, and the two safe-by-default readings of an unrecognised value are opposite: refusing
 * everything would empty the prompt silently, refusing nothing only makes it longer. The n8n
 * `Read Request` node rejects an unknown purpose at the edge so the value never gets this far.
 */
export function purposeAdmits(purpose, family) {
  // hasOwnProperty, not `?? []`: `PURPOSE_EXCLUDED_FAMILIES['constructor']` is a FUNCTION, not
  // undefined, so the nullish fallback would never fire and `.includes` would throw on a request
  // that named a purpose after an Object prototype member. Same idiom as conditionsMatch().
  if (!Object.prototype.hasOwnProperty.call(PURPOSE_EXCLUDED_FAMILIES, purpose)) return true

  return !PURPOSE_EXCLUDED_FAMILIES[purpose].includes(family)
}

/**
 * A pinned coordinate must equal the request's value; an unpinned one matches anything.
 *
 * A request that leaves a coordinate null means "no opinion", so a pinned rule is NOT in scope for
 * it — asking for brand-wide rules must not hand back one market's override.
 */
function scopeMatches(scope, ctx) {
  for (const dimension of SCOPE_DIMENSIONS) {
    const mine = scope?.[dimension] ?? null
    if (mine === null) continue
    const theirs = ctx[dimension] ?? null
    if (theirs === null || mine !== theirs) return false
  }
  return true
}

function isEffectiveAt(rule, asOf) {
  if (rule.effective_from === null && rule.effective_to === null) return true

  // FULL INSTANTS, compared exactly as PHP's KnowledgeRule::isEffectiveAt() compares them:
  //   expired      when  at >  effective_to
  //   not yet live when  at <  effective_from
  //
  // The earlier version sliced everything to a bare YYYY-MM-DD and reasoned that PHP kept a rule in
  // force through the end of its `effective_to` day. It does not — verified:
  // `new DateTimeImmutable('2026-08-20T14:32:10+00:00') > new DateTimeImmutable('2026-08-20')` is
  // true, so PHP treats such a rule as expired from that day's midnight. The JS kept it. Same
  // latent shape as the `supersedes` bug: no rule in the corpus is dated, so the conformance suite
  // could not see it, because both sides agreed by both doing nothing.
  //
  // The bounds are now exported as UTC RFC3339 instants rather than bare dates, so no guessing is
  // needed. Normalising both sides through Date().toISOString() makes the comparison chronological
  // regardless of the offset each side was written with — lexicographic ordering of Z-suffixed ISO
  // strings is chronological, and same-shape is what makes that safe.
  const at = normaliseInstant(asOf ?? new Date().toISOString())
  const from = normaliseInstant(rule.effective_from)
  const to = normaliseInstant(rule.effective_to)

  if (from !== null && at < from) return false
  if (to !== null && at > to) return false
  return true
}

/**
 * An ISO instant as a comparable, canonical UTC string.
 *
 * Accepts a bare `YYYY-MM-DD` too, and treats it as that day's midnight UTC — which is what PHP's
 * `new DateTimeImmutable('YYYY-MM-DD')` yields for a UTC process, and keeps an older bundle whose
 * bounds are still date-only comparing the same way PHP would.
 */
function normaliseInstant(value) {
  if (value === null || value === undefined || value === '') return null

  const iso = /^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T00:00:00Z` : value
  const parsed = new Date(iso)

  // An unparseable bound must not silently become "always in force": that would resurrect a retired
  // rule. Treated as absent and reported by the caller instead of guessed at.
  return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString()
}

/**
 * Mirrors ConditionEvaluator. Fails safe: a key the request says nothing about does NOT match, so a
 * market-availability condition cannot quietly pass when nobody supplied a market.
 */
export function conditionsMatch(appliesWhen, conditions) {
  for (const [key, expected] of Object.entries(appliesWhen ?? {})) {
    if (!Object.prototype.hasOwnProperty.call(conditions ?? {}, key)) return false
    if (!valueMatches(expected, conditions[key])) return false
  }
  return true
}

function valueMatches(expected, actual) {
  if (Array.isArray(expected)) return expected.some((c) => scalarMatches(c, actual))
  return scalarMatches(expected, actual)
}

function scalarMatches(expected, actual) {
  if (typeof expected === 'boolean' || typeof actual === 'boolean') {
    return asBool(expected) === asBool(actual)
  }
  if (isScalar(expected) && isScalar(actual)) return String(expected) === String(actual)
  return expected === actual
}

const isScalar = (v) => v !== null && (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean')

/** PHP's FILTER_VALIDATE_BOOLEAN with FILTER_NULL_ON_FAILURE, which is what the PHP side uses. */
function asBool(value) {
  if (typeof value === 'boolean') return value
  if (typeof value === 'number') return value === 1 ? true : value === 0 ? false : null
  if (typeof value !== 'string') return null
  const v = value.trim().toLowerCase()
  if (['1', 'true', 'on', 'yes'].includes(v)) return true
  if (['0', 'false', 'off', 'no', ''].includes(v)) return false
  return null
}

/**
 * Modality, then SLOT RELEVANCE, then channel relevance, then priority, then specificity, then key.
 * Mirrors RuleRanker.
 *
 * Two orderings exist deliberately. Conflict resolution asks "of the rules sharing a key, which is
 * in force?" and answers with specificity. Budget selection asks "of the rules in force, which
 * twelve reach the model?" and answers with obligation strength. One sort for both, specificity
 * first, was a silent correctness bug: ~70 product-layer rules against ~34 German language rules
 * meant the budget was exhausted by product messaging before it reached "use the Sie form". The
 * rules most expensive to break were the first evicted.
 *
 * The trailing key is what makes the sort total, and therefore what makes the output reproducible.
 */
export function rank(rules, slot = null, channel = null) {
  const binds = (declared, value) => (value === null || declared.length === 0 ? 0 : declared.includes(value) ? 1 : 0)

  return [...rules].sort(
    (a, b) =>
      MODALITY_WEIGHT[b.modality] - MODALITY_WEIGHT[a.modality] ||
      binds(b.slots, slot) - binds(a.slots, slot) ||
      binds(b.channels, channel) - binds(a.channels, channel) ||
      (b.priority ?? 0) - (a.priority ?? 0) ||
      b.specificity - a.specificity ||
      strcmp(a.key, b.key),
  )
}

/** PHP's strcmp: byte comparison. localeCompare would order differently under a different locale. */
function strcmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0
}

/**
 * Gathers same-family rules into one labelled line. Mirrors RuleCompactor.
 *
 * Compaction, not compression: nothing is reworded, summarised or merged in meaning. Six hyphenation
 * rules cost one line of twelve instead of six, and every instruction survives verbatim as a clause —
 * paraphrasing authored brand rules to save tokens would corrupt the thing being protected.
 */
export function toLines(ranked, minGroupSize = 2) {
  const byBucket = new Map()
  const firstSeen = new Map()

  ranked.forEach((rule, position) => {
    const bucket = NEVER_GROUP.has(rule.family) ? `${rule.family}#${rule.key}` : rule.family
    if (!byBucket.has(bucket)) {
      byBucket.set(bucket, [])
      firstSeen.set(bucket, position)
    }
    byBucket.get(bucket).push(rule)
  })

  const lines = []
  for (const [bucket, rules] of byBucket) {
    const family = bucket.split('#')[0]
    if (rules.length < minGroupSize) {
      for (const rule of rules) lines.push({ pos: firstSeen.get(bucket), line: promptLine(family, [rule]) })
      continue
    }
    lines.push({ pos: firstSeen.get(bucket), line: promptLine(family, rules) })
  }

  // Stable by construction: `pos` is a distinct insertion index per bucket, so no two entries tie
  // and Array.prototype.sort's stability guarantee is not being leaned on.
  lines.sort((a, b) => a.pos - b.pos)

  return lines.map((l) => l.line)
}

/** A line's modality is the STRONGEST among its rules — one `must` makes the line untruncatable. */
function promptLine(family, rules) {
  let modality = 'may'
  for (const rule of rules) {
    if (MODALITY_WEIGHT[rule.modality] > MODALITY_WEIGHT[modality]) modality = rule.modality
  }
  return { family, rules, modality }
}

/**
 * Rules that qualify this one and must travel with it.
 *
 * DIRECTION IS FIXED BY CONVENTION: an edge runs FROM the exception TO the general rule. So this
 * looks for OTHER surviving rules whose edges point AT this one. The convention exists because two
 * independent spike annotators created the same edge pointing opposite ways, both syntactically
 * valid, and no validator could tell them apart.
 *
 * An exception is NOT a drop. Both rules stay in the set, because a rule shipped without its
 * exception is confidently wrong — the German compounding case 3 defers to case 6, and a generator
 * seeing only case 3 hyphenates "WordPress Hosting" incorrectly.
 */
function exceptionsFor(rule, winners) {
  const out = []
  for (const candidate of winners.values()) {
    if (candidate === rule) continue
    for (const relation of candidate.relations ?? []) {
      if (relation.relation !== 'exception_to') continue
      if (relation.to !== rule.key) continue
      out.push(candidate)
    }
  }

  // Sorted by key, mirroring KnowledgeResolver::exceptionsFor(). Insertion order here is the order
  // of the rule index, which is stable — but PHP's insertion order is the order the DATABASE returned
  // candidates in, which is not. Both sides sort so the prompt bytes cannot diverge for a reason
  // that has nothing to do with resolution.
  out.sort((a, b) => strcmp(a.key, b.key))

  return out
}

function drop(rule, reason, beatenBy = null) {
  return {
    key: rule.key,
    specificity: rule.specificity,
    reason,
    modality: rule.modality,
    beaten_by: beatenBy,
    source_locator: rule.source_locator ?? null,
  }
}

// ── rendering ──────────────────────────────────────────────────────────────────────────────────────

/**
 * The block that goes into a prompt. Byte-identical to ResolvedRuleSet::forPrompt() — the conformance
 * fixture asserts these exact bytes, which is the strongest single check available here: it catches
 * an ordering divergence, a compaction divergence and a formatting divergence in one comparison.
 */
export function renderPrompt(lines) {
  return lines.map(renderLine).join('\n')
}

function renderLine(line) {
  if (line.rules.length === 1) return `- ${renderRule(line.rules[0])}`

  let out = `- [${line.modality.toUpperCase()}] ${familyLabel(line.family)}:`
  for (const rule of line.rules) {
    out += `\n    · ${rule.instruction}`
    if (rule.caveat !== null && rule.caveat !== undefined) out += ` (${rule.caveat})`
    for (const exception of rule.exceptions ?? []) out += `\n      Exception: ${exception.instruction}`
  }
  return out
}

function renderRule(rule) {
  let line = `[${rule.modality.toUpperCase()}] ${rule.instruction}`
  if (rule.caveat !== null && rule.caveat !== undefined) line += ` (${rule.caveat})`
  for (const exception of rule.exceptions ?? []) line += `\n    Exception: ${exception.instruction}`
  return line
}

/** PHP's ucfirst(str_replace('_', ' ', $family)) — ASCII-only, deliberately. */
function familyLabel(family) {
  const spaced = family.replace(/_/g, ' ')
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}

// ── repo plumbing ──────────────────────────────────────────────────────────────────────────────────

/**
 * Loads the rule index from a repo root.
 *
 * Parsed by `lib/yaml.mjs`, a reader written for exactly the subset the exporter emits. Pulling in a
 * YAML dependency would make this repo need an install step, and the whole point of a repo an agent
 * clones and works in is that `node scripts/...` runs immediately.
 */
export async function loadRules(repoRoot = '.') {
  const { parse } = await import('./yaml.mjs')
  const raw = await readFile(join(repoRoot, 'knowledge/rules/index.yaml'), 'utf8')
  return flattenIndex(parse(raw))
}
