// A reader for exactly the YAML subset this repo's exporter emits. Nothing more.
//
// WHY NOT A YAML LIBRARY. This repo is meant to be cloned and used immediately — `node scripts/…`
// has to work with no install step, or the first thing an agent hits is a dependency wall. So: no
// dependencies, anywhere.
//
// WHY YAML AT ALL, rather than JSON which needs no parser. The provenance header. Every generated
// file opens with "Generated by unima:knowledge:publish-agent-repo. DO NOT EDIT." and its source-row
// provenance, and JSON has no comments — the header would have to become a `_readme` key that a
// consumer could silently strip. A DO-NOT-EDIT notice that can be dropped by an object spread is not
// a notice.
//
// WHAT THIS PARSES — the whole grammar `Yaml::dump()` can produce, and deliberately nothing else:
//   - two-space indentation, block style only
//   - `key: scalar`, `key:` followed by a nested block, `key: []`, `key: {}`
//   - `- scalar`, and `-` on its own line followed by a nested map
//   - scalars: bare, or double-quoted with JSON escaping (Yaml::quote uses json_encode, and JSON
//     string escaping is a strict subset of YAML 1.2 double-quoted escaping)
//   - `true` / `false` / `null`, integers, floats
//   - `#` comment lines and blank lines
//
// WHAT IT REFUSES, loudly rather than silently: anchors, aliases, tags, flow collections with
// content, multi-line scalars, single-quoted strings, tabs. A silent misparse here would produce a
// wrong rule set with no error, which is the worst available outcome. An exception is strictly better.
//
// HOW IT IS PROVEN. `scripts/conformance.mjs` loads knowledge/rules/index.yaml through this parser
// and runs the whole conformance suite generated by the PHP resolver. A material misparse cannot
// pass that gate.

export function parse(text) {
  const lines = []

  text.split('\n').forEach((raw, i) => {
    if (raw.includes('\t')) {
      throw new YamlError(`tab character at line ${i + 1}. The exporter never emits tabs — this file has been hand-edited.`)
    }

    const trimmed = raw.trim()
    if (trimmed === '' || trimmed.startsWith('#')) return

    const indent = raw.length - raw.trimStart().length
    if (indent % 2 !== 0) {
      throw new YamlError(`odd indentation (${indent}) at line ${i + 1}. The exporter emits two spaces per level.`)
    }

    for (const forbidden of ['&', '*', '!!', '<<']) {
      if (trimmed.startsWith(forbidden)) {
        throw new YamlError(`unsupported YAML feature "${forbidden}" at line ${i + 1}.`)
      }
    }

    lines.push({ depth: indent / 2, text: trimmed, lineNo: i + 1 })
  })

  if (lines.length === 0) return {}

  const [value, consumed] = parseBlock(lines, 0, lines[0].depth)
  if (consumed !== lines.length) {
    throw new YamlError(`unconsumed content from line ${lines[consumed].lineNo}: "${lines[consumed].text}"`)
  }

  return value
}

/**
 * Parses one block at `depth`, returning [value, linesConsumed].
 *
 * A block is a mapping or a sequence, decided by whether its first line starts with "- ". Mixing the
 * two at one depth is a malformed file, and it is rejected rather than guessed at.
 */
function parseBlock(lines, start, depth) {
  const first = lines[start]
  if (first === undefined) return [null, 0]

  return first.text === '-' || first.text.startsWith('- ')
    ? parseSequence(lines, start, depth)
    : parseMapping(lines, start, depth)
}

function parseMapping(lines, start, depth) {
  const map = {}
  let i = start

  while (i < lines.length) {
    const line = lines[i]
    if (line.depth < depth) break
    if (line.depth > depth) {
      throw new YamlError(`unexpected indentation at line ${line.lineNo}: "${line.text}"`)
    }
    if (line.text.startsWith('- ') || line.text === '-') {
      throw new YamlError(`sequence item inside a mapping at line ${line.lineNo}.`)
    }

    const split = splitKey(line.text, line.lineNo)
    const key = split.key
    const rest = split.rest

    if (rest === '') {
      // `key:` with a nested block beneath, or an explicitly empty value at end of file.
      const next = lines[i + 1]
      if (next === undefined || next.depth <= depth) {
        map[key] = null
        i += 1
        continue
      }
      const [value, consumed] = parseBlock(lines, i + 1, next.depth)
      map[key] = value
      i += 1 + consumed
      continue
    }

    map[key] = scalar(rest, line.lineNo)
    i += 1
  }

  return [map, i - start]
}

function parseSequence(lines, start, depth) {
  const out = []
  let i = start

  while (i < lines.length) {
    const line = lines[i]
    if (line.depth < depth) break
    if (line.depth > depth) {
      throw new YamlError(`unexpected indentation at line ${line.lineNo}: "${line.text}"`)
    }
    if (!(line.text === '-' || line.text.startsWith('- '))) break

    if (line.text === '-') {
      // A bare dash: the item is the nested block below it. That is the shape Yaml::dump uses for a
      // list of maps, so this branch is the common one for rules/relations.
      const next = lines[i + 1]
      if (next === undefined || next.depth <= depth) {
        out.push(null)
        i += 1
        continue
      }
      const [value, consumed] = parseBlock(lines, i + 1, next.depth)
      out.push(value)
      i += 1 + consumed
      continue
    }

    out.push(scalar(line.text.slice(2).trim(), line.lineNo))
    i += 1
  }

  return [out, i - start]
}

/**
 * Splits `key: value` at the first colon that is not inside a quoted key.
 *
 * A quoted key can contain a colon (`Yaml::key()` quotes anything that is not
 * `[A-Za-z0-9_.\-/]+`), and splitting on the first colon unconditionally would truncate it.
 */
function splitKey(text, lineNo) {
  if (text.startsWith('"')) {
    const end = closingQuote(text, lineNo)
    const key = JSON.parse(text.slice(0, end + 1))
    const after = text.slice(end + 1)
    if (!after.startsWith(':')) {
      throw new YamlError(`expected ":" after quoted key at line ${lineNo}.`)
    }
    return { key, rest: after.slice(1).trim() }
  }

  const colon = text.indexOf(':')
  if (colon === -1) {
    throw new YamlError(`line ${lineNo} is neither a mapping nor a sequence item: "${text}"`)
  }

  return { key: text.slice(0, colon).trim(), rest: text.slice(colon + 1).trim() }
}

/** Index of the closing quote of a JSON-escaped double-quoted string starting at position 0. */
function closingQuote(text, lineNo) {
  for (let i = 1; i < text.length; i++) {
    if (text[i] === '\\') {
      i += 1
      continue
    }
    if (text[i] === '"') return i
  }
  throw new YamlError(`unterminated quoted string at line ${lineNo}.`)
}

function scalar(raw, lineNo) {
  if (raw === '') return null
  if (raw === '[]') return []
  if (raw === '{}') return {}

  if (raw.startsWith('"')) {
    const end = closingQuote(raw, lineNo)
    if (end !== raw.length - 1) {
      // Trailing content after a closing quote means either an inline comment (which the exporter
      // never emits) or a malformed line. Refuse rather than guess where the value ends.
      throw new YamlError(`trailing content after a quoted scalar at line ${lineNo}: "${raw}"`)
    }
    return JSON.parse(raw)
  }

  if (raw.startsWith("'")) {
    throw new YamlError(`single-quoted scalar at line ${lineNo}. The exporter only emits double quotes.`)
  }
  if (raw.startsWith('[') || raw.startsWith('{')) {
    throw new YamlError(`flow collection with content at line ${lineNo}. The exporter only emits block style.`)
  }
  if (raw === '|' || raw === '>' || raw.startsWith('|') || raw.startsWith('>')) {
    throw new YamlError(`block scalar at line ${lineNo}. The exporter quotes multi-line strings instead.`)
  }

  if (raw === 'null' || raw === '~') return null
  if (raw === 'true') return true
  if (raw === 'false') return false

  // Numbers, matching Yaml::looksScalar()'s numeric pattern so a round trip is lossless. Anything
  // else stays a string — including a bare word that happens to look like a version number.
  if (/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(raw)) {
    const n = Number(raw)
    return Number.isNaN(n) ? raw : n
  }

  return raw
}

export class YamlError extends Error {
  constructor(message) {
    super(`knowledge YAML: ${message}`)
    this.name = 'YamlError'
  }
}
