#!/usr/bin/env node
// The gate that makes lib/resolve.mjs legitimate instead of a second source of truth.
//
// knowledge/_conformance/cases.json is generated by Unima's PHP KnowledgeResolver — the normative
// implementation — and enumerates the contexts this corpus actually contains, each with the resolved
// key order, the check track, the drop reasons, the line count and the exact prompt bytes.
//
// This script replays every case through lib/resolve.mjs and fails on ANY divergence. A failure here
// is a bug in lib/resolve.mjs until proven otherwise. If you are certain PHP is wrong, fix PHP and
// regenerate — never edit a case to make this pass. That inverts the authority and the whole
// arrangement stops meaning anything.
//
//   node scripts/conformance.mjs            # all cases
//   node scripts/conformance.mjs --verbose  # print the first divergence in full
//   node scripts/conformance.mjs --case=17  # one case, by index

import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { argv, exit } from 'node:process'
import { loadRules, resolve } from '../lib/resolve.mjs'

const args = new Set(argv.slice(2))
const verbose = args.has('--verbose')
const only = [...args].find((a) => a.startsWith('--case='))
const onlyIndex = only ? Number(only.slice('--case='.length)) : null

const fixture = JSON.parse(await readFile('knowledge/_conformance/cases.json', 'utf8'))
const rules = await loadRules('.')

// ── pre-flight: does the port READ every field the exporter WRITES? ────────────────────────────────
//
// A defect class the case comparison structurally cannot catch. `supersedes` was emitted by the
// exporter and referenced by the walk, but was missing from flattenIndex()'s row mapping — so
// `rule.supersedes` was always `undefined`, supersession never fired in JS, and every case still
// agreed, because no rule in the corpus supersedes another. PHP and JS matched by both doing nothing.
//
// Any field the exporter adds and the port forgets fails the same silent way. So: diff the field sets
// before comparing a single case. A field the port deliberately ignores goes in IGNORED, which forces
// the decision to be written down rather than left as an omission.
const IGNORED_INDEX_FIELDS = new Set([
  'rationale', // human-facing only; forPrompt() deliberately omits it, so the port never needs it
  'specificity', // recomputed from scope: the stored value is a Postgres generated column, and an
  // in-memory row reads 0 — if the two disagree the arithmetic is what to trust
])

{
  const raw = await readFile('knowledge/rules/index.yaml', 'utf8')
  const { parse } = await import('../lib/yaml.mjs')
  const index = parse(raw)

  const emitted = new Set()
  for (const variants of Object.values(index.rules ?? {})) {
    for (const v of variants) for (const field of Object.keys(v)) emitted.add(field)
  }

  const read = new Set(rules.length > 0 ? Object.keys(rules[0]) : [])
  // flattenIndex renames one field on the way in; treat it as read.
  read.add('specificity')

  const dropped = [...emitted].filter((f) => !read.has(f) && !IGNORED_INDEX_FIELDS.has(f)).sort()

  if (dropped.length > 0) {
    console.error('conformance PRE-FLIGHT FAILED: lib/resolve.mjs does not read fields the exporter emits.\n')
    for (const field of dropped) console.error(`    knowledge/rules/index.yaml emits "${field}" — flattenIndex() drops it`)
    console.error('\nAdd each to flattenIndex()\'s row mapping, or to IGNORED_INDEX_FIELDS in this file')
    console.error('with a comment saying why the port does not need it. A silently dropped field makes')
    console.error('every case agree while the walk is missing an input.')
    exit(1)
  }
}

const cases = fixture.cases ?? []
if (cases.length === 0) {
  console.error('No conformance cases. Either the corpus is empty or the export is broken —')
  console.error('either way this is not a pass. Re-run unima:knowledge:publish-agent-repo.')
  exit(1)
}

// A cap the exporter applied is recorded in the fixture rather than left silent. Print it, because a
// truncated suite that looks complete is worse than a smaller suite that says so.
if (fixture.capped_at != null) {
  console.log(`note: the exporter capped this suite at ${fixture.capped_at} cases; ${fixture.dropped ?? '?'} were not emitted.`)
}

let passed = 0
const failures = []

cases.forEach((testCase, index) => {
  if (onlyIndex !== null && index !== onlyIndex) return

  const actual = resolve(rules, testCase.context)
  const expected = testCase.expected

  const divergences = []

  compareList(divergences, 'rule_keys', expected.rule_keys ?? [], actual.rules.map((r) => r.key))
  compareList(divergences, 'check_keys', expected.check_keys ?? [], actual.checks.map((r) => r.key))

  if (expected.line_count !== actual.line_count) {
    divergences.push(`line_count: expected ${expected.line_count}, got ${actual.line_count}`)
  }
  if (expected.candidate_count !== actual.candidate_count) {
    divergences.push(`candidate_count: expected ${expected.candidate_count}, got ${actual.candidate_count}`)
  }
  if (expected.mandatory_exceeds_budget !== actual.mandatory_exceeds_budget) {
    divergences.push(
      `mandatory_exceeds_budget: expected ${expected.mandatory_exceeds_budget}, got ${actual.mandatory_exceeds_budget}`,
    )
  }

  // The strongest single assertion available: the prompt block catches an ordering divergence, a
  // compaction divergence and a formatting divergence in one comparison.
  //
  // Compared by SHA for every case and by full bytes for the first few. The exporter records both,
  // because recording full bytes for every case produced a 40MB fixture and the target repo has to
  // stay committable — a hash catches the divergence just as well, it only cannot SHOW it. When the
  // bytes are present they are compared too, and that is what someone debugging reads.
  if (expected.prompt_sha256 !== undefined && sha256(actual.prompt) !== expected.prompt_sha256) {
    divergences.push(
      'prompt differs (sha256)' +
        (expected.prompt !== undefined
          ? `\n--- expected ---\n${expected.prompt}\n--- got ---\n${actual.prompt}`
          : '\n      (this case records a hash only — re-run the exporter with a higher VERBOSE_CASES,' +
            '\n       or use unima:knowledge:explain on this context, to see the full text)'),
    )
  } else if (expected.prompt !== undefined && expected.prompt !== actual.prompt) {
    // A hash match with a byte mismatch is impossible short of a collision; asserted anyway because
    // a silent disagreement between the two recorded forms would mean the exporter is inconsistent.
    divergences.push('prompt bytes differ while the sha256 matches — the fixture is internally inconsistent')
  }

  // Drops: compared as a sorted multiset, by hash for every case and by content where recorded.
  // Their emission ORDER is an artefact of which loop found them first and is not part of the
  // contract; their CONTENT is.
  const actualDropRows = actual.dropped.map((d) => ({
    key: d.key,
    reason: d.reason,
    modality: d.modality,
    beaten_by: d.beaten_by,
    specificity: d.specificity,
  }))

  if (expected.dropped_sha256 !== undefined && sha256(canonicalDrops(actualDropRows)) !== expected.dropped_sha256) {
    divergences.push(
      'dropped set differs (sha256)' +
        (expected.dropped !== undefined
          ? `\n--- expected ---\n${normaliseDrops(expected.dropped)}\n--- got ---\n${normaliseDrops(actualDropRows)}`
          : '\n      (hash only — see the note above)'),
    )
  }

  // A dropped MUST is recorded in full for every case, never hashed: it is a publish blocker rather
  // than a warning, so a divergence here has to be able to NAME the rule.
  const expectedMandatory = normaliseDrops(expected.dropped_mandatory ?? [])
  const actualMandatory = normaliseDrops(
    actualDropRows.filter((d) => d.modality === 'must' && d.reason === 'over_budget'),
  )
  if (expectedMandatory !== actualMandatory) {
    divergences.push(
      `dropped MANDATORY rules differ\n      expected: ${expectedMandatory || '(none)'}\n      got:      ${actualMandatory || '(none)'}`,
    )
  }

  if (divergences.length === 0) {
    passed += 1
    return
  }

  failures.push({ index, context: testCase.context, divergences })
})

const ran = onlyIndex !== null ? 1 : cases.length

if (failures.length === 0) {
  console.log(`conformance: ${passed}/${ran} cases agree with the PHP resolver.`)
  exit(0)
}

console.error(`conformance: ${failures.length} of ${ran} cases DIVERGE from the PHP resolver.\n`)

for (const failure of failures.slice(0, verbose ? failures.length : 5)) {
  console.error(`case ${failure.index}  ${describe(failure.context)}`)
  for (const d of failure.divergences) console.error(`    ${d}`)
  console.error('')
}

if (!verbose && failures.length > 5) {
  console.error(`… ${failures.length - 5} more. Re-run with --verbose.`)
}

console.error('lib/resolve.mjs is wrong until proven otherwise. Do not edit cases.json to make this pass.')
exit(1)

function compareList(into, label, expected, actual) {
  if (expected.length === actual.length && expected.every((v, i) => v === actual[i])) return

  // Order IS the assertion for these lists — it is the budget's selection order — so a set-equal but
  // differently-ordered result is a real failure and is reported as such rather than as "same items".
  const sameSet = expected.length === actual.length && [...expected].sort().join() === [...actual].sort().join()

  into.push(
    sameSet
      ? `${label}: same keys, WRONG ORDER\n      expected: ${expected.join(', ')}\n      got:      ${actual.join(', ')}`
      : `${label}:\n      expected: ${expected.join(', ') || '(none)'}\n      got:      ${actual.join(', ') || '(none)'}`,
  )
}

function normaliseDrops(drops) {
  return drops
    .map((d) => `${d.key}|${d.reason}|${d.modality ?? ''}|${d.beaten_by ?? ''}`)
    .sort()
    .join('\n')
}

/**
 * The exact string the exporter hashed: PHP's Yaml::inline() over the sorted drop list, which is
 * compact JSON. Field order and the sort must match the PHP side exactly or every case "diverges".
 */
function canonicalDrops(drops) {
  const sorted = [...drops].sort(
    (a, b) =>
      strcmp(a.key, b.key) ||
      strcmp(a.reason, b.reason) ||
      strcmp(a.modality ?? '', b.modality ?? '') ||
      strcmp(a.beaten_by ?? '', b.beaten_by ?? '') ||
      (a.specificity ?? 0) - (b.specificity ?? 0),
  )

  return JSON.stringify(
    sorted.map((d) => ({
      key: d.key,
      reason: d.reason,
      modality: d.modality,
      beaten_by: d.beaten_by ?? null,
      specificity: d.specificity ?? 0,
    })),
  )
}

function strcmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0
}

function sha256(value) {
  return createHash('sha256').update(value, 'utf8').digest('hex')
}

function describe(context) {
  const parts = []
  for (const key of ['language', 'market', 'product', 'audience_segment', 'slot', 'channel']) {
    if (context[key] != null) parts.push(`${key}=${context[key]}`)
  }
  parts.push(`budget=${context.budget ?? 12}`)
  return parts.join(' ')
}
